### ISSUE TITLE
[Bug] - Unable to complete Guide

### ISSUE THREAD

**Issue by sbtoonz** [heinermann/ValheimExportHelper#3]
Unable to complete asset ripping guide steps

Asset Ripper 2.1.0 reports error
```

ValheimExportHelper] Detected as Valheim

     'N@@N!``       '|@%M*`
       '] .         .WL   .,;,,   :@@mm~    ~g=~  ,;vy,,;;,, .;@,.k@@w- mmr  j@@@w
        '%/g,       i|'   `L]y'    '%\      j,:   '[[* '%@|;jF**T !RU  ;j%g, /&%L`
         'n]M     .)@L`   ,.'nu    .k:     'j$`   '[H  '|Rr`  .p  !N!  ;,r%@@$|K|
         ']@@r    !]@     \: |];   'OY      j|r  ;gMk  '|K,,=!~|| ;N|  ;$r' *`|@~
          '%#W,   [[     Cpx,*|k.  :n|      ]%UY[^`LK  '[[!`    ` *R|  |%U`   |g|
           `U]!  ,,``   /|=``  pp  'j@ .:r  ]|`   :F@   [[   zi@; ,J|  ;jL    [%~
            ]=N!.|@=   ,|k    '])' :\L'~:=|\]),   'F|   [!;;ij||* :lM  j@k   .[%y
            '||L`|!  ,(l*'     '```j``     '*^^   ~~-'  *~*       ***``'**`  '*]*`
            `j|%F:`  h|j$@@/::;ssssq/vFwgpgg@gps;Wgy=\w=wqw<#WW@zgpgwggwwgggg@@%|{
             'l|,`  ']M%****`*w%%~^'``''*H**TTT**q|)r*``````````*'**w%%*TTTTTT%MM`
               V                                 '|`

General : About to begin export to D:\NewShit\valheim
General : Removing any files from a previous export...
Export : Attempting to export assets to D:\NewShit\valheim...
Mono.Cecil.ResolutionException: Failed to resolve UnityEngine.Texture2D/EXRFlags
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream)
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver.CreatePEFile(AssemblyDefinition assembly) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 44
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(ReadOnlySpan`1 assemblies) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 20
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(IAssemblyManager manager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 15
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler..ctor(IAssemblyManager assemblyManager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 18
   at AssetRipper.Library.Exporters.Scripts.ScriptExporter..ctor(IAssemblyManager assemblyManager, LibraryConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExporter.cs:line 28
   at AssetRipper.Library.Ripper.OverrideNormalExporters() in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 302
   at AssetRipper.Library.Ripper.InitializeExporters() in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 251
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 165
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 154
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 52

General : About to begin export to D:\NewShit\valheim
General : Removing any files from a previous export...
Export : Attempting to export assets to D:\NewShit\valheim...
Mono.Cecil.ResolutionException: Failed to resolve UnityEngine.Texture2D/EXRFlags
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver.CreatePEFile(AssemblyDefinition assembly) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 44
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(ReadOnlySpan`1 assemblies) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 20
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(IAssemblyManager manager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 15
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler..ctor(IAssemblyManager assemblyManager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 18
   at AssetRipper.Library.Exporters.Scripts.ScriptExporter..ctor(IAssemblyManager assemblyManager, LibraryConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExporter.cs:line 28
   at AssetRipper.Library.Ripper.OverrideNormalExporters() in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 302
   at AssetRipper.Library.Ripper.InitializeExporters() in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 251
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 165
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 154
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 52
```

**Comment by sbtoonz** [comment]
I downloaded Asset ripper source for 0.2.1 
as well as source for this repo

Compiled both from source
installed plugin -> asset Ripper folder

identical results

**Comment by sbtoonz** [comment]
Trying to determine the failure point but debugging this is new to me. I will update this issue as I make progress

**Comment by heinermann** [comment]
Seems more like an AssetRipper bug to me. Which OS are you running on?

**Comment by sbtoonz** [comment]
> Seems more like an AssetRipper bug to me. Which OS are you running on?

Windows 10 home x64
AMD Ryzen 9 3900x
32gb of ram
Asset ripper functions 100% fine with the plugin removed and is able to rip the game 


Also validated it was not a permissions issue by letting AssetRipper run as admin and alternatively editing the filepath permissions so that "Everyone" had r/w access to the folder

neither yielded results

**Comment by heinermann** [comment]
😨

**Comment by sbtoonz** [comment]
Would also like to note adapting the plugin to V 0.2.2 yields same issue / error 

Horem was kind enough to share his completed game extract copy using your plugin. Which was how I was able to submit the PR's for usefulness when making assetbundles 



I also would like to note for you I attempted 2x scenario's 

1st) followed guide 100000% links and all 
Yielded this outcome

2nd) Followed guide (but got asset ripper from their git and checked out the tag for 0.2.1 and compiled it from source. Got your plugin and compiled it from source)
Yielded this outcome

**Comment by heinermann** [comment]
I have no idea how to repro or anything, I don't see anything helpful in the stack. I feel like my hands are tied for this issue unfortunately.

**Comment by sbtoonz** [comment]
Guess we will chalk it up to my env setup then 

I can try to spin a VM up and attempt to replicate there 

Will re open if i can replicate in a VM
